//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, enter a positive  integer number in the amount of URI textfiled.
        /// </summary>
        internal static string AmountOfURI_ToScan {
            get {
                return ResourceManager.GetString("AmountOfURI_ToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the target word field is empty.
        /// </summary>
        internal static string EmptySearchedString {
            get {
                return ResourceManager.GetString("EmptySearchedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} , node level is-{1}, number of node is-{2} , found words count is-{3} .
        /// </summary>
        internal static string ResultOfProcessing {
            get {
                return ResourceManager.GetString("ResultOfProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scarry {
            get {
                object obj = ResourceManager.GetObject("scarry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream scarry_sound {
            get {
                return ResourceManager.GetStream("scarry_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi user, it was a joke!!! Now you can proceed with the program execution by clicking START button.
        /// </summary>
        internal static string SorryMessage {
            get {
                return ResourceManager.GetString("SorryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been canceled!.
        /// </summary>
        internal static string TaskCanceled {
            get {
                return ResourceManager.GetString("TaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0} is starting.
        /// </summary>
        internal static string ThreadIsStarting {
            get {
                return ResourceManager.GetString("ThreadIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0} is stopping..
        /// </summary>
        internal static string ThreadIsStopping {
            get {
                return ResourceManager.GetString("ThreadIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, enter a positive integer number in the threads textfieled .
        /// </summary>
        internal static string ThreadValidationMessage {
            get {
                return ResourceManager.GetString("ThreadValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0} is processing node- {1}.
        /// </summary>
        internal static string ThredIsProcessingNode {
            get {
                return ResourceManager.GetString("ThredIsProcessingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found words count is-{0}.
        /// </summary>
        internal static string TotalFoundWords {
            get {
                return ResourceManager.GetString("TotalFoundWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you entered a not well-formed Uri (e.g. http(s)://example.com).
        /// </summary>
        internal static string WrongUriMessage {
            get {
                return ResourceManager.GetString("WrongUriMessage", resourceCulture);
            }
        }
    }
}
